### ISSUE TITLE
AT2 release ver. 2.3.57

### ISSUE THREAD

**Issue by argarak** [pdewacht/at2lpt#1]
There's a new version of adlib tracker 2 released last september, would be cool if it was possible to patch the new version to work with the opl3lpt and make a new release

changelog: http://adlibtracker.net/files/revision.htm

**Comment by pdewacht** [comment]
Hi! I don't intend to update this project anymore. Instead, I've added support for patching ADT2 to [ADPATCH].

The ADPATCH patches should keep working with future releases, as long as nothing changes in the low-level OPL3 routines. And I feel more confident about this approach, I never was confident I was recompiling ADT2 correctly.

[ADPATCH]: https://github.com/pdewacht/adlipt/
